"""empty message

Revision ID: 0d24a055ed61
Revises: f25999a522cb
Create Date: 2022-06-13 17:30:41.039046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d24a055ed61'
down_revision = 'f25999a522cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('title', sa.String(length=120), nullable=False))
    op.drop_constraint('book_titl_key', 'book', type_='unique')
    op.create_unique_constraint(None, 'book', ['title'])
    op.drop_column('book', 'titl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('titl', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'book', type_='unique')
    op.create_unique_constraint('book_titl_key', 'book', ['titl'])
    op.drop_column('book', 'title')
    # ### end Alembic commands ###
