"""empty message

Revision ID: 628f5ddffe8b
Revises: ddf9c9526c62
Create Date: 2022-06-21 13:28:15.242100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628f5ddffe8b'
down_revision = 'ddf9c9526c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
