"""empty message

Revision ID: 7191fc217d92
Revises: bbe913d5a13c
Create Date: 2022-06-11 14:00:56.640897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7191fc217d92'
down_revision = 'bbe913d5a13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###
