"""empty message

Revision ID: ee8b74230f5b
Revises: c74d8cfc50b5
Create Date: 2022-06-25 13:47:06.576896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8b74230f5b'
down_revision = 'c74d8cfc50b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_book',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='user_book_book_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_book_user_id_fkey')
    )
    # ### end Alembic commands ###
